<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $ip
     * @return null|User
     */
    public function findOneByIp($ip)
    {
        return $this->findOneBy(['ip' => $ip]);
    }

    /**
     * @param $username
     * @return null|User
     */
    public function findOneByUsername($username)
    {
        return $this->findOneBy(['username' => $username]);

    }
}
